server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/leyou
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
      host: 192.168.25.128
  rabbitmq:
    host: 192.168.25.128
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      retry:  #失败重试
        enabled: true  #开启失败重试
        initial-interval: 10000ms  #第一次重试的间隔时长
        max-interval: 210000ms  #最长重试间隔，超过这个间隔将不再重试
        multiplier: 2  #下次重试间隔的倍数，此处是2即下次重试间隔是上次的2倍
      exchange: leyou.user.exchange  #缺省的交换机名称，此处配置后，发送消息如果不指定交换机就会使用这个
    publisher-confirms: true  #生产者确认机制，确保消息会正确发送，如果发送失败会有错误回执，从而触发重试

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

mybatis:
  type-aliases-package: com.leyou.user.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

